gui:
    mouseEvents: false
    showRandomTip: false
    nerdFontsVersion: '3'
    showIcons: true
    skipDiscardChangeWarning: true
    sidePanelWidth: 0.25
git:
    branchLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --oneline {{branchName}}'
os:
    editPreset: 'nvim'
quitOnTopLevelReturn: true
promptToReturnFromSubprocess: false
